<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2010/05/26 15:33:28

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=SN',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
